const encodedData = "W3siaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6Ik5heWFudGhhcmEiLCJtb3ZpZSI6IkRhcmJhciIsInNvbmciOiJDaHVtbWEgS2l6aGkifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJLZWVydGh5IFN1cmVzaCIsIm1vdmllIjoiU2Fya2FyIiwic29uZyI6IlNpbXRhYW5nYXJhbiJ9LHsiaGVybyI6IkFqaXRoIiwiaGVyb2luZSI6IlNocmFkZGhhIFNyaW5hdGgiLCJtb3ZpZSI6Ik5lcmtvbmRhIFBhYXJ2YWkiLCJzb25nIjoiS2FhbGFtIn0seyJoZXJvIjoiRGhhbnVzaCIsImhlcm9pbmUiOiJNZWdoYSBBa2FzaCIsIm1vdmllIjoiRW5haSBOb2tpIFBhYXl1bSBUaG90YSIsInNvbmciOiJNYXJ1dmFhcnRoYWkifSx7Imhlcm8iOiJLYW1hbCBIYWFzYW4iLCJoZXJvaW5lIjoiU3JpZGV2aSIsIm1vdmllIjoiTW9vbmRyYW0gUGlyYWkiLCJzb25nIjoiS2FubmUgS2FsYWltYWFuZSJ9LHsiaGVybyI6IlZpa3JhbSIsImhlcm9pbmUiOiJBbXkgSmFja3NvbiIsIm1vdmllIjoiSSIsInNvbmciOiJFbm5vZHUgTmVlIElydW5kaGFhbCJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJTYW1hbnRoYSIsIm1vdmllIjoiQW5qYWFuIiwic29uZyI6IkJhbmcgQmFuZyBCYW5nIn0seyJoZXJvIjoiU2l2YWthcnRoaWtleWFuIiwiaGVyb2luZSI6Ik5heWFudGhhcmEiLCJtb3ZpZSI6Ik1yLiBMb2NhbCIsInNvbmciOiJLYWxha2thbHUgTXIuIExvY2FsdSJ9LHsiaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6IkFteSBKYWNrc29uIiwibW92aWUiOiJFbmRoaXJhbiAyLjAiLCJzb25nIjoiUHVsbGluYW5nYWwifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJUcmlzaGEiLCJtb3ZpZSI6IkdoaWxsaSIsInNvbmciOiJBcHBhZGkgUG9kdSJ9LHsiaGVybyI6IkthcnRoaSIsImhlcm9pbmUiOiJSYWt1bCBQcmVldCBTaW5naCIsIm1vdmllIjoiVGhlZXJhbiBBZGhpZ2FyYW0gT25kcnUiLCJzb25nIjoiTyBTYXRoaXllIn0seyJoZXJvIjoiQWppdGgiLCJoZXJvaW5lIjoiTmF5YW50aGFyYSIsIm1vdmllIjoiVmlzd2FzYW0iLCJzb25nIjoiQWRjaGl0aG9va3UifSx7Imhlcm8iOiJEaGFudXNoIiwiaGVyb2luZSI6IlNhaSBQYWxsYXZpIiwibW92aWUiOiJNYWFyaSAyIiwic29uZyI6IlJvd2R5IEJhYnkifSx7Imhlcm8iOiJTdXJpeWEiLCJoZXJvaW5lIjoiSnlvdGhpa2EiLCJtb3ZpZSI6IkthYWtoYSBLYWFraGEiLCJzb25nIjoiVXlpcmluIFV5aXJlIn0seyJoZXJvIjoiVmlrcmFtIiwiaGVyb2luZSI6IlNocml5YSBTYXJhbiIsIm1vdmllIjoiS2FudGhhc3dhbXkiLCJzb25nIjoiRXhjdXNlIE1lIE1yLiBLYW50aGFzd2FteSJ9LHsiaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6IlJhZGhpa2EgQXB0ZSIsIm1vdmllIjoiS2FiYWxpIiwic29uZyI6Ik5lcnVwcHUgRGEifSx7Imhlcm8iOiJLYXJ0aGkiLCJoZXJvaW5lIjoiVGFtYW5uYWFoIiwibW92aWUiOiJQYWl5YWEiLCJzb25nIjoiRW4gS2FkaGFsIFNvbGxhIn0seyJoZXJvIjoiQWppdGgiLCJoZXJvaW5lIjoiSHVtYSBRdXJlc2hpIiwibW92aWUiOiJWYWxpbWFpIiwic29uZyI6Ik5hYW5nYSBWZXJhIE1hYXJpIn0seyJoZXJvIjoiU2l2YWthcnRoaWtleWFuIiwiaGVyb2luZSI6IkFudSBFbW1hbnVlbCIsIm1vdmllIjoiTmFtbWEgVmVldHR1IFBpbGxhaSIsInNvbmciOiJNYWlsYWFuamkifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJBbnVzaGthIFNoZXR0eSIsIm1vdmllIjoiVmV0dGFpa2FhcmFuIiwic29uZyI6IlB1bGkgVXJ1bXVkaHUifSx7Imhlcm8iOiJEaGFudXNoIiwiaGVyb2luZSI6IkFtYWxhIFBhdWwiLCJtb3ZpZSI6IlZlbGFpaWxsYSBQYXR0YWRoYXJpIiwic29uZyI6IkFtbWEgQW1tYSJ9LHsiaGVybyI6IkthbWFsIEhhYXNhbiIsImhlcm9pbmUiOiJTaW1yYW4iLCJtb3ZpZSI6IlBhbW1hbCBLLiBTYW1iYW5kYW0iLCJzb25nIjoiS2FkaGFsIFBpc2FzZSJ9LHsiaGVybyI6IlZpa3JhbSIsImhlcm9pbmUiOiJUcmlzaGEiLCJtb3ZpZSI6IlNhYW15Iiwic29uZyI6IlRoaXJ1bmVsdmVsaSBBbHdhIERoYWFuIn0seyJoZXJvIjoiUmFqaW5pa2FudGgiLCJoZXJvaW5lIjoiS3VzaGJvbyIsIm1vdmllIjoiTWFubmFuIiwic29uZyI6IkFkaWt1dGh1IEt1bGlydSJ9LHsiaGVybyI6IlZpamF5IFNldGh1cGF0aGkiLCJoZXJvaW5lIjoiTWFkb25uYSBTZWJhc3RpYW4iLCJtb3ZpZSI6IkthZGhhbHVtIEthZGFuZGh1IFBvZ3VtIiwic29uZyI6IkthIEthIEthIFBvIn0seyJoZXJvIjoiQWppdGgiLCJoZXJvaW5lIjoiVGFtYW5uYWFoIiwibW92aWUiOiJWZWVyYW0iLCJzb25nIjoiTmFsbGF2YW5udSBTb2x2YWFuZ2EifSx7Imhlcm8iOiJTdXJpeWEiLCJoZXJvaW5lIjoiUHJpeWEgQW5hbmQiLCJtb3ZpZSI6Ik1hbmthdGhhIiwic29uZyI6IlZpbGF5YWR1IE1hbmthdGhhIn0seyJoZXJvIjoiRGhhbnVzaCIsImhlcm9pbmUiOiJQYXJ2YXRoeSBUaGlydXZvdGh1IiwibW92aWUiOiJNYXJ5YW4iLCJzb25nIjoiSW5udW0gS29uamFtIE5lcmFtIn0seyJoZXJvIjoiS2FydGhpIiwiaGVyb2luZSI6IkthamFsIEFnZ2Fyd2FsIiwibW92aWUiOiJBbGwgaW4gQWxsIEF6aGFndSBSYWphIiwic29uZyI6IllhYXJ1a2t1bSBUaG96aGFuIn0seyJoZXJvIjoiU2l2YWthcnRoaWtleWFuIiwiaGVyb2luZSI6IlNhbWFudGhhIiwibW92aWUiOiJTZWVtYXJhamEiLCJzb25nIjoiVmFydW0gQWFuYSBWYXJhYXRodSJ9LHsiaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6IkFudXNoa2EgU2hldHR5IiwibW92aWUiOiJMaW5nYWEiLCJzb25nIjoiTW9uYSBHYXNvbGluYSJ9LHsiaGVybyI6IlZpamF5IiwiaGVyb2luZSI6IkhhbnNpa2EgTW90d2FuaSIsIm1vdmllIjoiUHVsaSIsInNvbmciOiJZYWVuZGkgWWFlbmRpIn0seyJoZXJvIjoiQWppdGgiLCJoZXJvaW5lIjoiVHJpc2hhIiwibW92aWUiOiJZZW5uYWkgQXJpbmRoYWFsIiwic29uZyI6IkFkaGFhcnUgQWRoYWFydSJ9LHsiaGVybyI6IkRoYW51c2giLCJoZXJvaW5lIjoiUmljaGEgR2FuZ29wYWRoeWF5IiwibW92aWUiOiJNYXlha2thbSBFbm5hIiwic29uZyI6IlZvZGEgVm9kYSJ9LHsiaGVybyI6IlZpa3JhbSIsImhlcm9pbmUiOiJBbXkgSmFja3NvbiIsIm1vdmllIjoiSXJ1IE11Z2FuIiwic29uZyI6IkhhbGVuYSJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJUYW1hbm5hYWgiLCJtb3ZpZSI6IkF5YW4iLCJzb25nIjoiVml6aGkgTW9vZGkifSx7Imhlcm8iOiJLYXJ0aGkiLCJoZXJvaW5lIjoiUmFrdWwgUHJlZXQgU2luZ2giLCJtb3ZpZSI6IkRldiIsInNvbmciOiJBbmFuZ2UifSx7Imhlcm8iOiJTaXZha2FydGhpa2V5YW4iLCJoZXJvaW5lIjoiUHJpeWEgQW5hbmQiLCJtb3ZpZSI6IkV0aGlyIE5lZWNoYWwiLCJzb25nIjoiTmlqYW1lbGxhbSBNYXJhbnRodXBvY2h1In0seyJoZXJvIjoiUmFqaW5pa2FudGgiLCJoZXJvaW5lIjoiU2hyaXlhIFNhcmFuIiwibW92aWUiOiJTaXZhamkiLCJzb25nIjoiU2FoYW5hIFNhYXJhbCJ9LHsiaGVybyI6IlZpamF5IiwiaGVyb2luZSI6IkFzaW4iLCJtb3ZpZSI6IlBva2tpcmkiLCJzb25nIjoiQWFkdW5nYWRhIn0seyJoZXJvIjoiRGhhbnVzaCIsImhlcm9pbmUiOiJBaXNod2FyeWEgUmFqZXNoIiwibW92aWUiOiJWYWRhIENoZW5uYWkiLCJzb25nIjoiRW5nYSBWZWV0dSBLdXRodXZpbGFra3UifSx7Imhlcm8iOiJBaml0aCIsImhlcm9pbmUiOiJLYWphbCBBZ2dhcndhbCIsIm1vdmllIjoiVml2ZWdhbSIsInNvbmciOiJTdXJ2aXZhIn0seyJoZXJvIjoiVmlrcmFtIiwiaGVyb2luZSI6IkFudXNoa2EgU2hldHR5IiwibW92aWUiOiJEZWl2YSBUaGlydW1hZ2FsIiwic29uZyI6IkFhcmlybyBBYXJhcmlybyJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJBbnVzaGthIFNoZXR0eSIsIm1vdmllIjoiU2luZ2FtIiwic29uZyI6IlN0b2xlIE15IEhlYXJ0In0seyJoZXJvIjoiUmFqaW5pa2FudGgiLCJoZXJvaW5lIjoiQWlzaHdhcnlhIFJhaSIsIm1vdmllIjoiRW50aGlyYW4iLCJzb25nIjoiQXJpbWEgQXJpbWEifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJBbXkgSmFja3NvbiIsIm1vdmllIjoiVGhlcmkiLCJzb25nIjoiSml0aHUgSmlsbGFkaSJ9LHsiaGVybyI6IkFqaXRoIiwiaGVyb2luZSI6Ik1hbmp1IFdhcnJpZXIiLCJtb3ZpZSI6IlRodW5pdnUiLCJzb25nIjoiQ2hpbGxhIENoaWxsYSJ9LHsiaGVybyI6IlNpdmFrYXJ0aGlrZXlhbiIsImhlcm9pbmUiOiJIYW5zaWthIE1vdHdhbmkiLCJtb3ZpZSI6Ik1hYW4gS2FyYXRlIiwic29uZyI6Ik9wZW4gdGhlIFRhc21hYyJ9LHsiaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6Ik5heWFudGhhcmEiLCJtb3ZpZSI6IktvY2hhZGFpaXlhYW4iLCJzb25nIjoiTW9uYSBHYXNvbGluYSJ9LHsiaGVybyI6IlZpamF5IiwiaGVyb2luZSI6IlNhbWFudGhhIiwibW92aWUiOiJUaHVwcGFra2kiLCJzb25nIjoiT3J1IFZldHJpIEF0aGljaHVkaSJ9LHsiaGVybyI6IkFqaXRoIiwiaGVyb2luZSI6IlNocnV0aSBIYWFzYW4iLCJtb3ZpZSI6IlZlZGFsYW0iLCJzb25nIjoiQWFsdW1hIERvbHVtYSJ9LHsiaGVybyI6IkRoYW51c2giLCJoZXJvaW5lIjoiS2VlcnRoeSBTdXJlc2giLCJtb3ZpZSI6Ik5lbmUgUmFqdSBOZW5lIE1hbnRyaSIsInNvbmciOiJOYWFuIFlhYXIifSx7Imhlcm8iOiJLYW1hbCBIYWFzYW4iLCJoZXJvaW5lIjoiQW5kcmVhIEplcmVtaWFoIiwibW92aWUiOiJWaXNod2Fyb29wYW0iLCJzb25nIjoiVW5uYWkgS2FhbmFkaHUgTmFhbiJ9LHsiaGVybyI6IlZpa3JhbSIsImhlcm9pbmUiOiJTaHJ1dGkgSGFhc2FuIiwibW92aWUiOiJTYWFteSBTcXVhcmUiLCJzb25nIjoiQWF0aGljaHVkaSJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJLYWphbCBBZ2dhcndhbCIsIm1vdmllIjoiU2luZ2FtIElJIiwic29uZyI6Ik5lbmp1a2t1bCBQZWlkaGlkdW0ifSx7Imhlcm8iOiJTaXZha2FydGhpa2V5YW4iLCJoZXJvaW5lIjoiS2FqYWwgQWdnYXJ3YWwiLCJtb3ZpZSI6Ik1hYW4gS2FyYXRlIiwic29uZyI6Ik9wZW4gdGhlIFRhc21hYyJ9LHsiaGVybyI6IlJhamluaWthbnRoIiwiaGVyb2luZSI6Ik5heWFudGhhcmEiLCJtb3ZpZSI6IkJhYXNoYSIsInNvbmciOiJOYWFuIEF1dG9rYWFyYW4ifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJTaHJpeWEgU2FyYW4iLCJtb3ZpZSI6IkF6aGFnaXlhIFRhbWlsIE1hZ2FuIiwic29uZyI6Ikl0aHUgS2FhZGhhbCBLYWFkaGFsIn0seyJoZXJvIjoiQWppdGgiLCJoZXJvaW5lIjoiVHJpc2hhIiwibW92aWUiOiJNYW5rYXRoYSIsInNvbmciOiJNYWNoaSBPcGVuIHRoZSBCb3R0bGUifSx7Imhlcm8iOiJEaGFudXNoIiwiaGVyb2luZSI6IkFtYWxhIFBhdWwiLCJtb3ZpZSI6IkV0aGlyIE5lZWNoYWwiLCJzb25nIjoiTmlqYW1lbGxhbSBNYXJhbnRodXBvY2h1In0seyJoZXJvIjoiS2FtYWwgSGFhc2FuIiwiaGVyb2luZSI6IlNpbXJhbiIsIm1vdmllIjoiUGFtbWFsIEsuIFNhbWJhbmRhbSIsInNvbmciOiJLYWRoYWwgUGlzYXNlIn0seyJoZXJvIjoiVmlrcmFtIiwiaGVyb2luZSI6Ik5heWFudGFyYSIsIm1vdmllIjoiTWFubWFkaGFuIEFtYnUiLCJzb25nIjoiVmVubmlsYXZlIn0seyJoZXJvIjoiU3VyaXlhIiwiaGVyb2luZSI6IlNocnV0aSBIYWFzYW4iLCJtb3ZpZSI6IjdhYW0gQXJpdnUiLCJzb25nIjoiT3J1IE5hYWwgUG9kaHVtYSJ9LHsiaGVybyI6IlNpdmFrYXJ0aGlrZXlhbiIsImhlcm9pbmUiOiJOYXlhbnRoYXJhIiwibW92aWUiOiJLZWRpIEJpbGxhIEtpbGxhZGkgUmFuZ2EiLCJzb25nIjoiS2VkaSBCaWxsYSBLaWxsYWRpIFJhbmdhIn0seyJoZXJvIjoiUmFqaW5pa2FudGgiLCJoZXJvaW5lIjoiVHJpc2hhIiwibW92aWUiOiJLb2NoYWRhaWl5YWFuIiwic29uZyI6Ik1vbmEgR2Fzb2xpbmEifSx7Imhlcm8iOiJWaWpheSIsImhlcm9pbmUiOiJOaXRoeWEgTWVuZW4iLCJtb3ZpZSI6Ik5pbmFpdGhhYWxlIEluaWtrdW0iLCJzb25nIjoiVmVubmlsYXZlIFZlbm5pbGF2ZSJ9LHsiaGVybyI6IkFqaXRoIiwiaGVyb2luZSI6Ik5heWFudGhhcmEiLCJtb3ZpZSI6IkFlZ2FuIiwic29uZyI6IkFhdGhpY2h1ZGkifSx7Imhlcm8iOiJEaGFudXNoIiwiaGVyb2luZSI6Ik1lZ2hhIEFrYXNoIiwibW92aWUiOiJFbm5haSBOb2traSBQYWF5dW0gVGhvdGEiLCJzb25nIjoiTWFydXZhYXJ0aGFpIn0seyJoZXJvIjoiS2FtYWwgSGFhc2FuIiwiaGVyb2luZSI6IlBvb2phIEt1bWFyIiwibW92aWUiOiJWaXNod2Fyb29wYW0gSUkiLCJzb25nIjoiVW5uYWkgS2FhbmFkaHUgTmFhbiJ9LHsiaGVybyI6IlZpa3JhbSIsImhlcm9pbmUiOiJBbXkgSmFja3NvbiIsIm1vdmllIjoiSXJ1IE11Z2FuIiwic29uZyI6IkhhbGVuYSJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJLYWphbCBBZ2dhcndhbCIsIm1vdmllIjoiQXlhbiIsInNvbmciOiJWaXpoaSBNb29kaSJ9LHsiaGVybyI6IlNpdmFrYXJ0aGlrZXlhbiIsImhlcm9pbmUiOiJQcml5YSBBbmFuZCIsIm1vdmllIjoiRXRoaXIgTmVlY2hhbCIsInNvbmciOiJOaWphbWVsbGFtIE1hcmFudGh1cG9jaHUifSx7Imhlcm8iOiJSYWppbmlrYW50aCIsImhlcm9pbmUiOiJBaXNod2FyeWEgUmFpIiwibW92aWUiOiJFbnRoaXJhbiIsInNvbmciOiJBcmltYSBBcmltYSJ9LHsiaGVybyI6IlZpamF5IiwiaGVyb2luZSI6IlNocnV0aSBIYWFzYW4iLCJtb3ZpZSI6IlRoZXJpIiwic29uZyI6IkppdGh1IEppbGxhZGkifSx7Imhlcm8iOiJBaml0aCIsImhlcm9pbmUiOiJLYWphbCBBZ2dhcndhbCIsIm1vdmllIjoiVml2ZWdhbSIsInNvbmciOiJTdXJ2aXZhIn0seyJoZXJvIjoiRGhhbnVzaCIsImhlcm9pbmUiOiJSaWNoYSBHYW5nb3BhZGh5YXkiLCJtb3ZpZSI6Ik1heWFra2FtIEVubmEiLCJzb25nIjoiVm9kYSBWb2RhIn0seyJoZXJvIjoiVmlrcmFtIiwiaGVyb2luZSI6IkFudXNoa2EgU2hldHR5IiwibW92aWUiOiJEZWl2YSBUaGlydW1hZ2FsIiwic29uZyI6IkFhcmlybyBBYXJhcmlybyJ9LHsiaGVybyI6IlN1cml5YSIsImhlcm9pbmUiOiJBbnVzaGthIFNoZXR0eSIsIm1vdmllIjoiU2luZ2FtIiwic29uZyI6IlN0b2xlIE15IEhlYXJ0In0seyJoZXJvIjoiU2l2YWthcnRoaWtleWFuIiwiaGVyb2luZSI6IkhhbnNpa2EgTW90d2FuaSIsIm1vdmllIjoiTWFhbiBLYXJhdGUiLCJzb25nIjoiT3BlbiB0aGUgVGFzbWFjIn1d";

let movies = []; // This will store the movie data
let currentMovieIndex = -1;
let score = 0;

// Decode the obfuscated movie data
function decodeData(base64String) {
  const jsonString = atob(base64String);  // Decode Base64
  return JSON.parse(jsonString);          // Parse JSON
}

// Initialize the movies data from encoded data
movies = decodeData(encodedData);
getRandomMovie(); // Start the game


function getRandomMovie() {
  if (movies.length === 0) {
    console.error("No movies available.");
    return;
  }
  currentMovieIndex = Math.floor(Math.random() * movies.length);
  updateQuestionBoxes();
}

function updateQuestionBoxes() {
  const movie = movies[currentMovieIndex];
  document.getElementById("a11").innerText = movie.hero.charAt(0);
  document.getElementById("a12").innerText = movie.heroine.charAt(0);
  document.getElementById("a21").innerText = movie.movie.charAt(0);
  document.getElementById("a22").innerText = movie.song.charAt(0);

  // Clear input fields
  document.getElementById("heroInput").value = "";
  document.getElementById("heroineInput").value = "";
  document.getElementById("movieInput").value = "";
  document.getElementById("songInput").value = "";
}

function checkAnswer() {
  const movie = movies[currentMovieIndex];
  const heroAnswer = document.getElementById("heroInput").value.trim().toLowerCase();
  const heroineAnswer = document.getElementById("heroineInput").value.trim().toLowerCase();
  const movieAnswer = document.getElementById("movieInput").value.trim().toLowerCase();
  const songAnswer = document.getElementById("songInput").value.trim().toLowerCase();

  if (heroAnswer === movie.hero.toLowerCase() &&
      heroineAnswer === movie.heroine.toLowerCase() &&
      movieAnswer === movie.movie.toLowerCase() &&
      songAnswer === movie.song.toLowerCase()) {
    score += 4;
    alert("Correct! You earned 4 marks.");
    loadNextQuestion();
  } else {
    alert("Incorrect answer. Try again.");
  }
  updateScore();
}

function loadNextQuestion() {
  getRandomMovie();
}

function updateScore() {
  document.getElementById("score").innerText = "Score: " + score;
}

// Track if a hint has been used for the current question

let hintUsed = false; 

function giveHint() {
  if (!hintUsed) { // Only allow one hint per question
    const movie = movies[currentMovieIndex];
    document.getElementById("heroInput").value = movie.hero; // Set the hero's name in the input field
    score -= 1; // Deduct 1 points for using a hint
    updateScore();
    hintUsed = true; // Mark hint as used
  } else {
    alert("Hint already used for this question!");
  }
}

function loadNextQuestion() {
  hintUsed = false; // Reset hint status for the next question
  getRandomMovie();
}

